version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: umbra_postgres_db
    environment:
      POSTGRES_DB: learning_platform_db
      POSTGRES_USER: learning_user
      POSTGRES_PASSWORD: umbra
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployment/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: umbra_fastapi_app
    command: bash -c "alembic upgrade head && uvicorn src.api.v1.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: learning_platform_db
      DB_USER: learning_user
      DB_PASSWORD: umbra
      # MLFLOW_TRACKING_URI: http://mlflow:5000 # Uncomment if MLflow server is added
    depends_on:
      db:
        condition: service_healthy
    # Uncomment and configure if you plan to use an MLflow tracking server within Docker
    # mlflow:
    #   image: ghcr.io/mlflow/mlflow:latest
    #   container_name: umbra_mlflow_server
    #   ports:
    #     - "5000:5000"
    #   environment:
    #     MLFLOW_TRACKING_URI: "http://0.0.0.0:5000"
    #     AWS_ACCESS_KEY_ID: your_access_key # Replace with your actual AWS credentials or remove if not using S3 backend
    #     AWS_SECRET_ACCESS_KEY: your_secret_key
    #   volumes:
    #     - ./mlruns:/mlruns

volumes:
  postgres_data: 