services:
  db:
    image: postgres:13-alpine
    container_name: umbra_postgres_db
    environment:
      POSTGRES_DB: umbra_db
      POSTGRES_USER: umbra_user
      POSTGRES_PASSWORD: secure_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umbra_user -d umbra_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: umbra_fastapi_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn src.api.v1.main:app --host 0.0.0.0 --port 8000 --reload # --reload for local development

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile # Assuming there's a Dockerfile inside the frontend folder
    container_name: umbra_streamlit_app
    ports:
      - "8501:8501" # Default Streamlit port
    depends_on:
      - backend # Assuming frontend needs backend to be running
    environment:
      BACKEND_URL: http://backend:8000 # Points to the backend service within Docker network

volumes:
  postgres_data:
    driver: local 