"""Add url to Course model

Revision ID: ac2ecae5f28f
Revises: 62d8e5bba881
Create Date: 2025-06-12 17:01:51.330506

"""
<<<<<<< HEAD

=======
>>>>>>> 63e865f (Initial commit: Umbra Educational Data Platform)
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD
revision: str = "ac2ecae5f28f"
down_revision: Union[str, None] = "62d8e5bba881"
=======
revision: str = 'ac2ecae5f28f'
down_revision: Union[str, None] = '62d8e5bba881'
>>>>>>> 63e865f (Initial commit: Umbra Educational Data Platform)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD
    op.add_column("courses", sa.Column("url", sa.String(), nullable=True))
    op.create_unique_constraint(None, "courses", ["url"])
=======
    op.add_column('courses', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'courses', ['url'])
>>>>>>> 63e865f (Initial commit: Umbra Educational Data Platform)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD
    op.drop_constraint(None, "courses", type_="unique")
    op.drop_column("courses", "url")
=======
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'url')
>>>>>>> 63e865f (Initial commit: Umbra Educational Data Platform)
    # ### end Alembic commands ###
